services:
  - type: worker
    name: cc-pro-ultra-2025
    env: python
    region: singapore
    plan: pro ultra     # or pro-ultra if you pay $450+
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    numInstances: 1
    disk:
      name: ultra-vault
      mountPath: /data
      sizeGB: 10
    envVars:
      YOUR_BOT_TOKEN:
        value: "8435079339:AAGjDyIWrIbwq5v-Z6Qg6tfNQfF1cqiJMCY"
      ADMIN_USER_ID:
        value: "7307757609"
      SELL_CHANNEL_ID:
        value: "-1003288341144"
      BOT_NAME:
        value: "@ccscraps123_bot"